assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
install: |
  sudo apt-get -y update
  sudo gem install pdd
release:
  script: |-
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/twee/version.rb
    git add lib/twee/version.rb
    git commit -m "version set to ${tag}"
    gem build twee.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - yegor256
architect:
- yegor256
merge:
  script: |-
    bundle install
    rake
    pdd
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
